### ISSUE TITLE
The event processors to read messages from a queue should be of type 'org.axonframework.messaging.StreamableMessageSource'

### ISSUE THREAD

**Issue by Macrame** [AxonFramework/extension-amqp#2]
I upgraded to Axon-framework 4.3. When I tried to start the application an exception occurs.
```
Caused by: org.springframework.beans.factory.BeanNotOfRequiredTypeException: Bean named 'insuranceUserQueueMessageSource' is expected to be of type 'org.axonframework.messaging.StreamableMessageSource' but was actually of type 'com.xxxx.config.configuration.AxonRabbitConfiguration$1'
```
Bellow is my configuration:
```
   @Bean
    public SpringAMQPMessageSource insuranceResidentQueueMessageSource(Serializer serializer){
        return new SpringAMQPMessageSource(serializer){
            @RabbitListener(queues = "${axon.amqp.queue.xxxx.event}")
            @Override
            public void onMessage(Message message, Channel channel) {
                logger.debug("Message received: "+message.toString());
                super.onMessage(message, channel);
            }
        };
    }
```
and
```
axon:
    ...
    # consumption configuration for query side
    eventhandling:
        processors:
            xxxx-name:
                source: xxxx-queue-name
```

I read the documentation in [Axon.io](https://docs.axoniq.io/reference-guide/extensions/spring-amqp) and did not find any new examples about this.
